sudo: false
dist: trusty
language: go
go:
  - 1.5.3
  - 1.6rc1
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  allow_failures:
    - go: tip

script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - sh files/go-fmt-check.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
