sudo: false
dist: trusty
language: go
go:
  - 1.5.3
  - 1.6rc1
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  allow_failures:
    - go: tip

script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - gofmt -l . | read && echo "Code differs from gofmt's style" 1>&2 && exit 1 || true
