sudo: false
dist: trusty
language: go
go:
  - 1.5.3
  - 1.6rc1
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  allow_failures:
    - go: tip

after_success:
  - test -f build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f build/coverage/full.cov
