sudo: false
dist: trusty
language: go
go:
  - 1.5.3
  - 1.6rc1
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  allow_failures:
    - go: tip

script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - git diff HEAD^ --name-status | grep "^D" -v | sed 's/^.\t//g' | grep "\.go$" | while read FILE; do go fmt $FILE; done
  - git diff --exit-code --quiet
