sudo: false
dist: trusty
language: go
go:
  - 1.5.3
  - 1.6rc1
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  allow_failures:
    - go: tip

before_install:
  - pip install --user codecov

after_success:
  - codecov
